paths:
  raw_energy: "../data/raw/energy_dataset.csv"
  raw_weather: "../data/raw/weather_features.csv"
  output_dir: "../data/processed/"
  log_dir: "../logs/exp_main_ra_st_glru/"
  result_dir: "../results/"

preprocessing:
  target_col: "total load actual"
  cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao"]
  split_ratio: [0.8, 0.1, 0.1]

model:
  seq_len: 168     # 保持 168，这是成功的关键
  out_len: 24
  top_k: 5
  use_retrieval: True
  
  # [调整] 
  d_model: 64        # 32 -> 64 (有了时间特征，模型需要更多神经元来处理)
  layers: 2          # 1 -> 2 (加深一层，提取更抽象的时间-负荷关系)
  
  in_features: 44    # 这里的数字不重要，脚本会自动检测 (会变成 30+3=33)
  dropout: 0.2       # 0.2 是折中方案，既不至于欠拟合(0.4)，也不至于过拟合(0.1)

train:
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.001 # 保持强正则化
  patience: 15