paths:
  raw_energy: "../data/raw/energy_dataset.csv"
  raw_weather: "../data/raw/weather_features.csv"
  output_dir: "../data/processed/"
  log_dir: "../logs/exp_main_ra_st_glru/"
  result_dir: "../results/"

preprocessing:
  target_col: "total load actual"
  cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao"]
  split_ratio: [0.8, 0.1, 0.1]

model:
  seq_len: 168
  out_len: 24
  top_k: 3
  use_retrieval: True
  d_model: 64        # [修改] 64 -> 32 (瘦身)
  layers: 2          # [修改] 2 -> 1 (防止过深)
  in_features: 40    # 自动检测
  dropout: 0.2       # [修改] 0.3 -> 0.4 (加大力度丢弃，强正则化)

train:
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.001
  patience: 15       # [修改] 稍微给多点耐心，因为我们要加 Scheduler 了